// keyvectors prints a Solidity library of Monero (private spend key, public spend key)
// pairs generated with Athanor's mcrypto package, for testing XmrSwap's on-chain check.
package main

import (
	"encoding/hex"
	"fmt"
	"os"
	"strings"

	mcrypto "github.com/athanorlabs/atomic-swap/crypto/monero"
)

func main() {
	const n = 32
	secrets := make([]string, 0, n+1)
	pubs := make([]string, 0, n+1)

	// edge vector: scalar 1 -> the ed25519 base point
	one := make([]byte, 32)
	one[0] = 1
	sk1, err := mcrypto.NewPrivateSpendKey(one)
	if err != nil {
		panic(err)
	}
	secrets = append(secrets, hex.EncodeToString(sk1.Bytes()))
	pubs = append(pubs, hex.EncodeToString(sk1.Public().Bytes()))

	for i := 0; i < n; i++ {
		kp, err := mcrypto.GenerateKeys()
		if err != nil {
			panic(err)
		}
		sk, err := mcrypto.NewPrivateSpendKey(kp.SpendKeyBytes())
		if err != nil {
			panic(err)
		}
		secrets = append(secrets, hex.EncodeToString(sk.Bytes()))
		pubs = append(pubs, hex.EncodeToString(sk.Public().Bytes()))
	}

	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: MIT\npragma solidity 0.8.28;\n\n")
	b.WriteString("// GENERATED by contracts-v2/tools/keyvectors using Athanor's mcrypto. Do not edit.\n")
	b.WriteString("// Each secret is a Monero private spend key; each pub is its public spend key,\n")
	b.WriteString("// both in Monero byte order.\n")
	b.WriteString("library KeyVectors {\n")
	fmt.Fprintf(&b, "    uint256 internal constant N = %d;\n\n", len(secrets))
	b.WriteString("    function secrets() internal pure returns (bytes32[] memory s) {\n        s = new bytes32[](N);\n")
	for i, s := range secrets {
		fmt.Fprintf(&b, "        s[%d] = 0x%s;\n", i, s)
	}
	b.WriteString("    }\n\n    function pubs() internal pure returns (bytes32[] memory p) {\n        p = new bytes32[](N);\n")
	for i, p := range pubs {
		fmt.Fprintf(&b, "        p[%d] = 0x%s;\n", i, p)
	}
	b.WriteString("    }\n}\n")

	if err := os.WriteFile("contracts-v2/test/KeyVectors.sol", []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %d vectors; vector 0 pub (should be ed25519 base point 5866…66): %s\n", len(secrets), pubs[0])
}
